version: 2.1

env:
  SERVER_IP: 10.100.15.152

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest
    
    environment:
      CI: false

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm install --save react-chartjs-2 chart.js
      - run: npm run build -- --output-path=build
      - run: ls build

      # run tests!
      #- run: npm run build
      - run:
          name: Run Tests
          command: npm test -- --coverage || true

      - run:
          name: Upload coverage report to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

      - run:
          name: Install Firebase CLI
          command: |
            sudo npm install -g firebase-tools

      - run:
          name: Deploy to Firebase
          command: |
            echo $FIREBASE_TOKEN > /tmp/firebase-service-account.json
            firebase deploy --only hosting --project testing-e6ee0 --non-interactive --token "$(cat /tmp/firebase-service-account.json)"
          environment:
            GOOGLE_APPLICATION_CREDENTIALS: /tmp/firebase-service-account.json
